name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-13
    strategy:
        matrix:
          destination: ['platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro']
    steps:
      - name: Force xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'dev'
      - name: Build
        run: |
          xcodebuild clean build -project YTeam.xcodeproj -scheme YTeam -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
      - name: Test
        run: |
          xcodebuild clean test -project YTeam.xcodeproj -scheme GHFollowersTests -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination }}
