name: CI-Test

on: [push]

jobs:
  test:
    name: Test
    runs-on: macos-13
    strategy:
        matrix:
          destination1: ['platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro']
          destination2: ['platform=watchOS Simulator,OS=10.0,name=Apple Watch Series 7 (45mm)']
    steps:
      - name: Force xcode
        run: sudo xcode-select -switch /Applications/Xcode_15.0.app
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: Build iOS
        run: |
          xcodebuild clean build -project YTeam.xcodeproj -scheme YTeam -destination "${destination}" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination1 }}
      - name: Build WatchOS
        run: |
           xcodebuild clean build -project YTeam.xcodeproj -scheme "YTeam Watch App" -destination "${destination}" -configuration Debug CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
         destination: ${{ matrix.destination2 }}
